# Generated by Django 5.1 on 2024-09-21 22:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_question_type_remove_question_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz_score',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('selected_option', models.CharField(max_length=255)),
                ('correct_option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
