# Generated by Django 4.2.11 on 2024-09-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_question_topic_user_userquizresult_and_more'),
    ]

    operations = [
    ]
