# Generated by Django 5.1 on 2024-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizresult_quiz_score_quizresult_date_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
