# Generated by Django 5.1 on 2024-09-24 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
