# Generated by Django 5.1 on 2024-09-25 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizresult_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
